model_name: logistic_regression
params:
  penalty: l2
  C: 1.0
  solver: liblinear
  max_iter: 100
fairness:
  protected_attribute: gender
  fairness_metric: equal_opportunity
  mitigation: equalized_odds_postprocessing
_meta:
  created_at: '2025-06-03T14:18:32.395262Z'
  author: Bias Buster Pro
