model_name: random_forest
params:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  random_state: 42
fairness:
  protected_attribute: gender
  fairness_metric: equal_opportunity
  mitigation: equalized_odds_postprocessing
_meta:
  created_at: '2025-06-03T14:18:32.398648Z'
  author: Bias Buster Pro
